/* Generated by Yosys 0.38+113 (git sha1 91fbd5898, clang++ 14.0.0-1ubuntu1.1 -fPIC -Os) */

module full_adder(A, B, Cin, Sum, Cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input A;
  wire A;
  input B;
  wire B;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output Sum;
  wire Sum;
  assign _04_ = A ^ B;
  assign Sum = _04_ ^ Cin;
  assign _00_ = A & B;
  assign _01_ = B & Cin;
  assign _03_ = _00_ | _01_;
  assign _02_ = A & Cin;
  assign Cout = _03_ | _02_;
endmodule

module ripple_carry_adder(A, B, Cin, Sum, Cout);
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  wire [7:0] Carry;
  input Cin;
  wire Cin;
  output Cout;
  wire Cout;
  output [7:0] Sum;
  wire [7:0] Sum;
  full_adder FA0 (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .Cout(Carry[0]),
    .Sum(Sum[0])
  );
  full_adder FA1 (
    .A(A[1]),
    .B(B[1]),
    .Cin(Carry[0]),
    .Cout(Carry[1]),
    .Sum(Sum[1])
  );
  full_adder FA2 (
    .A(A[2]),
    .B(B[2]),
    .Cin(Carry[1]),
    .Cout(Carry[2]),
    .Sum(Sum[2])
  );
  full_adder FA3 (
    .A(A[3]),
    .B(B[3]),
    .Cin(Carry[2]),
    .Cout(Carry[3]),
    .Sum(Sum[3])
  );
  full_adder FA4 (
    .A(A[4]),
    .B(B[4]),
    .Cin(Carry[3]),
    .Cout(Carry[4]),
    .Sum(Sum[4])
  );
  full_adder FA5 (
    .A(A[5]),
    .B(B[5]),
    .Cin(Carry[4]),
    .Cout(Carry[5]),
    .Sum(Sum[5])
  );
  full_adder FA6 (
    .A(A[6]),
    .B(B[6]),
    .Cin(Carry[5]),
    .Cout(Carry[6]),
    .Sum(Sum[6])
  );
  full_adder FA7 (
    .A(A[7]),
    .B(B[7]),
    .Cin(Carry[6]),
    .Cout(Cout),
    .Sum(Sum[7])
  );
endmodule
